export const GLOBAL_TEXT = {
  scenarios: "Сценарии",
  create_scenario: "Создать новый сценарий",
  no_scenarios: "Нет сценариев",
  creating: "Создание...",
  name: "Название",
  updatedAt: "Дата обновления",
  delete_scenario: "Удалить сценарий",
  page_not_found: "Страница не найдена",
  back_to_list: "Назад к списку",
  script_editor: "Редактор сценария",
  action: "Действие",
  new_action: "Новое действие",
  action_desc: "Описание действия",
  condition: "Условие",
  new_condition: "Новое условие",
  condition_desc: "Описание условия",
};
